### PR TITLE
Ensure scala file is on disk

### PR DESCRIPTION
**Pull request by ckipp01**
@lewis6991 much better idea. Regarding

> Do we need to also update the autocmds so the relevant ones are buffer local?

I don't _believe_ this should be an issue, but which ones did you have in mind?

### CODE REVIEW

**Comment by lewis6991** [comment]
I needed to make the autocmds buffer local to prevent the error:

```
Error detected while processing CursorHold Autocommands for "*.scala":
RPC[Error] code_name = MethodNotFound, message = "method textDocument/documentHighlight is not supported by any of the servers registered for the current buffer"
```

Because even though we don't attach to non-existent files, the autocmds will be already set up for all buffers. Also given since the autocmds are setup each time we attach to a buffer, it doesn't make sense for them to be global.

Steps to produce:
1. Open a scala file on disk which nvim-metals will attach to. This sets up the autocmds for all *.scala files.
2. Run `Gitsigns diffthis`. Autocmds trigger for this buffer even though nvim-metals doesn't attach.

**Comment by lewis6991** [comment]
Additionally, any autocmds that need to be global should be setup outside of the attach callback.

**Comment by ckipp01** [comment]
Huh, yea that makes sense. I'm a bit fuzzy on autocmds and need to learn them better. I was actually having issues with one firing in the past
```lua
  api.nvim_command([[autocmd BufEnter <buffer> lua require'metals'.did_focus()]])
```
Because when I'd navigate back to a file, it wouldn't fire again causing issues. So making them global actually didn't happen that long ago.

https://github.com/scalameta/nvim-metals/pull/164/files

The error about the document highlighting I hit on every once in a while, and yea we should fix that. 

I'm assuming changing these two to be buffer local will fix the issue.

```lua
  api.nvim_command([[autocmd CursorHold  *.scala lua vim.lsp.buf.document_highlight()]])
  api.nvim_command([[autocmd CursorMoved *.scala lua vim.lsp.buf.clear_references()]])
```

**Comment by lewis6991** [comment]
And this one too:

```lua
  api.nvim_command([[autocmd BufEnter,CursorHold,InsertLeave *.scala <buffer> lua vim.lsp.codelens.refresh()]])
```

**Pull request merged**
